### ISSUE TITLE
-output option should specify a file name, not a directory.

### ISSUE THREAD

**Issue by nkinkade** [m-lab/gcs-downloader#3]
Currently, the `-output` options specifies a directory, and the file specified by `-source` is written to that directory. This doesn't offer much flexibility if you want the file written to disk to have a different name than the file name in GCS. I would propose that the `-output` option specify the absolute path and name of the file to be written to allow more flexibility.

**Comment by stephen-soltesz** [comment]
Maybe "gcs-sync" would be a better name than "gcs-downloader" -- my intent was to download GCS files individually or in bulk but not support renaming any individual file.

So, I think this is not a feature I'd like to support. And, I think renaming files this way falls into the same category for me as my general dislike of name translations :)
